# Generated by Django 5.2.2 on 2025-06-18 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_adminuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminuser',
            name='mobile_number',
        ),
        migrations.AddField(
            model_name='adminuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
