# Generated by Django 5.2.2 on 2025-06-24 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_remove_section_degree_remove_section_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.department'),
        ),
    ]
