# Generated by Django 5.2.2 on 2025-07-16 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_alter_section_department_alter_student_degree_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentnotificationstatus',
            name='notification',
        ),
        migrations.RemoveField(
            model_name='studentnotificationstatus',
            name='student',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='StudentNotificationStatus',
        ),
    ]
