# Generated by Django 5.2.2 on 2025-07-19 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_adminmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
