services:
  - type: web
    name: django-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn vrbackend.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: vrbackend.settings
    
    