# Generated by Django 5.2.2 on 2025-08-29 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_feature_remove_plan_duration_months_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='duration_months',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
