# Generated by Django 5.2.2 on 2025-08-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_plan_duration_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
