"""
Django settings for vrbackend project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-7lp4f=u_d+656k-v5p9w(**b9k1c9ogj7_gn%_(7u=6=%xvlp!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'students',
    'captcha',
     'channels',
    'student_panel',
   ]
#WEBSOCKET_FOR ADMIN TO STUDENTS_NOTIFICATION
ASGI_APPLICATION = 'vrbackend.asgi.application'
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)],
        },
    },
}


RECAPTCHA_PUBLIC_KEY = '6LcNu2wrAAAAALkFcSfQmqcNH0ypeoio3o1eV0Fs'
RECAPTCHA_PRIVATE_KEY = '6LcNu2wrAAAAACQdbuM1dYiOkyAE143FMWXW_KFL'
JAZZMIN_SETTINGS = {
    "site_title": "Training Admin",
    "site_header": "Student Training Dashboard",
    "welcome_sign": "Welcome to the Training System",

    # Theme for clean, minimal look
    "theme": "litera",  # 'litera' is a light, elegant, clean theme

    # Custom icons
    "icons": {
        "students.Student": "fas fa-user-graduate",
        "students.Module": "fas fa-cogs",
        "students.Session": "fas fa-clock",
        "students.Degree": "fas fa-graduation-cap",
        "students.Department": "fas fa-building",
        "students.Section": "fas fa-th-list",
        "students.AdminUser": "fas fa-user-shield",
    },
    # Optional: Add your own CSS tweaks
    "custom_css": "css/custom_admin.css",

    # UI Enhancements
    "list_display_links": ["id", "name"],
    "related_modal_active": True,
    "show_ui_builder": False,
}

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]
# Add this line:
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',

]
CORS_ALLOW_ALL_ORIGINS = True  # Allow Unity calls

ROOT_URLCONF = 'vrbackend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'vrbackend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'abinesh70103@gmail.com'  # 👉 your email
EMAIL_HOST_PASSWORD = 'wvtx mzgz libs yrmo'  # 👉 app password (not your regular password)
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
LOGIN_URL = '/login/'
